services:
  # Backend API Service
  - type: web
    name: macchiato-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build:render
    startCommand: npm run start:render
    healthCheckPath: /health
    envVars:
      # Server Configuration
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      
      # Database Configuration (Render PostgreSQL)
      - key: DATABASE_URL
        fromDatabase:
          name: macchiato-db
          property: connectionString
      - key: PGHOST
        fromDatabase:
          name: macchiato-db
          property: host
      - key: PGUSER
        fromDatabase:
          name: macchiato-db
          property: user
      - key: PGDATABASE
        fromDatabase:
          name: macchiato-db
          property: database
      - key: PGPASSWORD
        fromDatabase:
          name: macchiato-db
          property: password
      - key: PGPORT
        fromDatabase:
          name: macchiato-db
          property: port
      
      # Supabase Configuration (Primary Database)
      - key: SUPABASE_URL
        value: https://whiijcszqrggkesbfjdg.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoaWlqY3N6cXJnZ2tlc2JmamRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDk1OTIsImV4cCI6MjA2Mjg4NTU5Mn0.YEo-BuIvq4gLoEqdk1UVF9Gsz0bhMVIdgPCdk2VfNmI
      
      # JWT Configuration
      - key: JWT_SECRET
        value: macchiato_suites_jwt_secret_key_2024_secure_token_for_authentication
      - key: JWT_EXPIRES_IN
        value: 7d
      
      # CORS Configuration
      - key: CORS_ORIGIN
        value: https://macchiato-delta.vercel.app
      
      # Cloudinary Configuration
      - key: CLOUDINARY_CLOUD_NAME
        value: dji23iymw
      - key: CLOUDINARY_API_KEY
        value: "153258216349693"
      - key: CLOUDINARY_API_SECRET
        value: 8NOP8q7Rve2FjOomgk8j84sXFCk
      
      # Security Configuration
      - key: BCRYPT_SALT_ROUNDS
        value: "12"
      - key: SESSION_SECRET
        value: macchiato_session_secret_key_2024_secure
      
      # File Upload Configuration
      - key: MAX_FILE_SIZE
        value: "5242880"
      - key: ALLOWED_FILE_TYPES
        value: image/jpeg,image/png,image/webp,image/jpg
      
      # Rate Limiting Configuration
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"

databases:
  # PostgreSQL Database
  - name: macchiato-db
    databaseName: macchiato_3xko
    user: macchiato_3xko_user
    plan: starter
