name = "macchiato-backend"
main = "dist/worker-simple.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "macchiato-backend"

[env.staging]
name = "macchiato-backend-staging"

# Environment variables (set these using wrangler secret put)
# SUPABASE_URL
# SUPABASE_ANON_KEY
# JWT_SECRET
# CLOUDINARY_CLOUD_NAME
# CLOUDINARY_API_KEY
# CLOUDINARY_API_SECRET

# Bindings for external services
[[env.production.bindings]]
name = "SUPABASE_URL"
type = "secret"

[[env.production.bindings]]
name = "SUPABASE_ANON_KEY"
type = "secret"

[[env.production.bindings]]
name = "JWT_SECRET"
type = "secret"

[[env.production.bindings]]
name = "CLOUDINARY_CLOUD_NAME"
type = "secret"

[[env.production.bindings]]
name = "CLOUDINARY_API_KEY"
type = "secret"

[[env.production.bindings]]
name = "CLOUDINARY_API_SECRET"
type = "secret"
