// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whiijcszqrggkesbfjdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoaWlqY3N6cXJnZ2tlc2JmamRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDk1OTIsImV4cCI6MjA2Mjg4NTU5Mn0.YEo-BuIvq4gLoEqdk1UVF9Gsz0bhMVIdgPCdk2VfNmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);